apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: a-team-postgres
  namespace: a-team
spec:
  id: a-team-postgres
  compositionSelector:
    matchLabels:
      provider: google
      db: postgres
  parameters:
    version: "13"
    size: small
